<?php

/**
 * @file
 * Contains pendo.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\Entity\User;

/**
 * Implements hook_help().
 */
function pendo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pendo module.
    case 'help.page.pendo':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides integration with Pendo software.') . '</p>';
      return $output;

    default:
  }
}

/**
 * @param $variables
 */
function pendo_preprocess_html(&$variables) {
  $variables['#attached']['library'][] = 'pendo/pendo-js';
  $variables['#attached']['drupalSettings']['pendo']['api_key'] = \Drupal::config('pendo.settings')->get('api_key');
  $variables['#attached']['drupalSettings']['pendo']['data']['visitor']['id'] = User::load(\Drupal::currentUser()->id())->uuid();
  $variables['#attached']['drupalSettings']['pendo']['data']['visitor']['email'] = \Drupal::currentUser()->getEmail();

  putenv('AH_SITE_GROUP=eemgrasmick');
  // Acquia.
  $acquia_env_vars = [
    'AH_CURRENT_REGION',
    'AH_SITE_NAME',
    'AH_APPLICATION_UUID',
    'AH_REALM',
    'AH_NON_PRODUCTION',
    'AH_SITE_ENVIRONMENT',
    'AH_SITE_GROUP',
  ];
  foreach ($acquia_env_vars as $value) {
    if (getenv($value) !== FALSE) {
      $variables['#attached']['drupalSettings']['pendo']['data']['account'][$value] = getenv($value);
    }
  }
}
