<?php

/**
 * @file
 * Contains pendo.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\Entity\User;

/**
 * Implements hook_help().
 */
function pendo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pendo module.
    case 'help.page.pendo':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides integration with Pendo software.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function pendo_theme() {
  return [
    'pendo' => [
      'variables' => [
        'api_key' => \Drupal::config('pendo.settings')->get('api_key'),
        'visitor' => [
          'email' => NULL,
          'id' => NULL,
          'full_name' => NULL,
          'role' => NULL,
          'other' => [],
        ],
        'account' => [
          'id' => \Drupal::config('system.site')->get('uuid'),
          'name' => NULL,
          'is_paying' => NULL,
          'monthly_value' => NULL,
          'planLevel' => NULL,
          'planPrice' => NULL,
          'creationDate' => NULL,
          'other' => [],
        ]
      ],
    ],
  ];
}

/**
 * Implements hook_page_bottom().
 */
function pendo_page_bottom(array &$page_bottom){
  // As per pendo instructions, this script must appear exactly once on all pages.
  $page_bottom['pendo'] = array(
    '#theme' => 'pendo',
  );
  $page_bottom['pendo']['visitor']['id'] = User::load(\Drupal::currentUser()->id())->uuid();
  $page_bottom['pendo']['visitor']['email'] = \Drupal::currentUser()->getEmail();

  putenv('AH_SITE_GROUP=eemgrasmick');
  // Acquia.
  $acquia_env_vars = [
    'AH_CURRENT_REGION',
    'AH_SITE_NAME',
    'AH_APPLICATION_UUID',
    'AH_REALM',
    'AH_NON_PRODUCTION',
    'AH_SITE_ENVIRONMENT',
    'AH_SITE_GROUP',
  ];
  foreach ($acquia_env_vars as $value) {
    if (getenv($value) !== FALSE) {
      $page_bottom['pendo']['account']['other'][$value] = getenv($value);
    }
  }
}
